---
# - name: Hello World Sample
#   become: true
#   tasks:

- hosts: 192.168.7.80
  become: true
  tasks:
     - name: pull changes
       shell: chdir=/webhookTest git pull https://github.com/setyooadji19/webhookTest.git testing
#    - name: copy readme to localhost
#      copy:
#        src: README.md
#        dest: /etc/README.md
#      when: tower_webhook_payload.ref == "refs/heads/main"
    
- hosts: 192.168.7.81 
  become: true
  tasks:
   - name: copy readme to rakha
     copy:
       src: README.md
       dest: /etc/README.md
     when: tower_webhook_payload.ref == "refs/heads/testing"

