---
# - name: Hello World Sample
#   become: true
#   tasks:

- hosts: 192.168.7.80
  become: true
  tasks:
   - name: copy readme
     copy:
       src: README.md
       dest: /etc/README.md
     when: tower_webhook_payload.ref == "refs/heads/main"
    
- hosts: 192.168.7.81 
  become: true
  tasks:
   - name: copy readme
     copy:
       src: README.md
       dest: /etc/README.md
     when: tower_webhook_payload.ref == "refs/heads/Testing"

#   - name: Run apt update via shell
#     shell: apt update
#     become: yes
    
    
    
    
    #   tasks:
#    - name: Hello Message
#      debug:
#        msg: "Hello World!" 


#     - include: Main.yml
#       when: tower_webhook_payload.ref == "refs/heads/main"
