---
- name: Hello World Sample
  hosts: all
  become: true
  tasks:
  - name: Copy readme file
    host: 192.168.7.80
    copy:
      src: README.md
      dest: /etc/README.md
    when: tower_webhook_payload.ref == "refs/heads/main"

  - name: Run apt update via shell
    shell: apt update
    become: yes
    
    #   tasks:
#    - name: Hello Message
#      debug:
#        msg: "Hello World!"

