---
- name: Hello World Sample
  hosts: all
  become: true
  tasks:
   - name: Hello Message
     debug:
       msg: "Hello World!"
#   tasks:
#   - name: Copy txt file
#     copy:
#       src: /etc/ansible/text.txt
#       dest: /etc/text2.txt

#   - name: Run apt update via shell
#     shell: apt update
#     become: yes

